name: Generate Badges

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight
  workflow_dispatch:

jobs:
  generate-badges-downloads:
    name: Downloads
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install numerize requests

      # script creates directory gh-pages/badges/downloads
      - name: Generate badges
        run: python .github/workflows/scripts/generate_badges_downloads.py

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: gh-pages-badges-downloads
          path: gh-pages/badges/

  # Example job for generating a second set of badges. Do not forget to add to "needs" of the actual deploy job below.
  # generate-badges-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

  #     - name: Set up Python
  #       uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
  #       with:
  #         python-version: '3.x'

  #     # script creates directory gh-pages/badges/test
  #     - name: Generate badges
  #       run: python .github/workflows/scripts/generate_badges_test.py

  #     - name: Upload artifact
  #       uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
  #       with:
  #         name: gh-pages-badges-test
  #         path: gh-pages/badges/

  deploy-pages:
    name: Deploy Badges
    needs: [generate-badges-downloads]
    uses: ./.github/workflows/deploy-pages.yml
    with:
      identifier: "badges"
